### ISSUE TITLE
With 1-level headings all are class=h6

### ISSUE THREAD

**Issue by flyingflo** [willfaught/paige#104]
Hi,

thanks for your great work on this theme!

I found that in a simple article with only one level of headings, all are shifted to class=h6 no matter of how they are marked in markdown. E.g. `##` becomes `<h2 class="h6"..`
This mapping is done is this relatively fresh part of layouts/_default/_markup/[render-heading.html](https://github.com/willfaught/paige/blob/c73cba40eb7b87f883b6f3b57b0de08f4f6018fa/layouts/_default/_markup/render-heading.html#L26)

All headings are shifted such that the lowest level is h6. I'm not sure what the rationale is. 
Anyways, it has the drawback, that in a simple article with just a few headings on the same level, everything becomes h6 and therefore very unimportant. To get a `h1` I need to have all 6 levels somewhere in the markdown file.
Probably I just don't understand it!?

Thanks,
Florian

**Comment by willfaught** [comment]
Hi @flyingflo, thanks for your report.

I added that behavior so that you don't get huge heading sizes when only using one heading level like `## Foo`.

It seems that the issue is that the h6-styled headings look unimportant. By that, do you mean that they appear too small? Not bold enough? It isn't clear that they are headings? Is there a screenshot you can share?

Paige uses Bootstrap classes, so the styles of the h1 through h6 classes are used for the h1 through h6 elements anyway if heading level 6 is used in the page's Markdown. Would you still see an issue with how h6 elements are displayed in that case?

Note that the page title is displayed in an h1 element, so Markdown headings must start at level 2. This is common in Hugo, and probably anywhere else that stores page titles outside of Markdown.

**Comment by pbj-writes** [comment]
@willfaught Following up on this, I was using a CSS file to style my headers, but it's not working since I took several updates. I'm wondering then how do I customize the bootstrap classes so I can, for instance, have different colors for different headings across my site?

**Comment by willfaught** [comment]
>However, it might be better to adapt bootstrap's h6 style.

@flyingflo I'm not sure what this means. Are you suggesting an idea?

I see that you changed that webpage to use a larger font size for the headers. Did you decide that the h6 size was too small in the case of a Markdown document that has only one heading level? If so, would it be useful to have an option to disable this heading resizing feature?

>I'm wondering then how do I customize the bootstrap classes so I can, for instance, have different colors for different headings across my site?

@pbj-writes Heading elements were styled with Bootstrap classes that used `!important`, so the color couldn't be overridden. I just released a fix in v0.111.0. Please try it now.

**Comment by flyingflo** [comment]
> I see that you changed that webpage to use a larger font size for the headers. Did you decide that the h6 size was too small in the case of a Markdown document that has only one heading level? If so, would it be useful to have an option to disable this heading resizing feature?

@willfaught As a quick fix, I limited the level reduction to 4, because I wanted bigger headings in this case (now they are `h4`). 

I'm still not sure what's best. Probably a on/off option or an option to set the base class, like I did from 6 to 4. However, that is very sophisticated and hard to explain to others. On/Off might be enough, because Off would give the markdown source full control over the heading classes.

**Comment by jezcope** [comment]
I've just run across this and the problem I find is that if I only have one level of heading they all become h6-styled, which makes them indistinguishable from the surrounding text, though this may depend on the font in use. For example:

![Image](https://github.com/user-attachments/assets/0461852a-ef82-4dd5-996e-d3c67a140204)

I marked this up as a h2 (`## Meet the team`) because I wanted a h2-sized heading. 😉 I worked around it by overriding the `render-heading.html` template but I agree it would be better to have a param that could disable/tweak it at the site or page level. Maybe something like:

```toml
[params.paige.page]
normalize_headings = false
```

to disable it entirely, and

```toml
[params.paige.page]
normalize_headings = 4
```

to specify the heading level to normalize to?

**Comment by pbj-writes** [comment]
> > However, it might be better to adapt bootstrap's h6 style.
> 
> [@flyingflo](https://github.com/flyingflo) I'm not sure what this means. Are you suggesting an idea?
> 
> I see that you changed that webpage to use a larger font size for the headers. Did you decide that the h6 size was too small in the case of a Markdown document that has only one heading level? If so, would it be useful to have an option to disable this heading resizing feature?
> 
> > I'm wondering then how do I customize the bootstrap classes so I can, for instance, have different colors for different headings across my site?
> 
> [@pbj-writes](https://github.com/pbj-writes) Heading elements were styled with Bootstrap classes that used `!important`, so the color couldn't be overridden. I just released a fix in v0.111.0. Please try it now.

@willfaught Just was able to implement a fix. Thanks for the fix and thanks for a dope theme!

**Comment by willfaught** [comment]
@flyingflo @pbj-writes @jezcope Sorry for the delay responding. I decided this behavior would be unexpected and perhaps unwanted for a not-insignificant number of users, so per @jezcope's suggestion, I turned the feature off by default. It can be enabled and configured like so, also documented in the readme:

```tool
[paige.pages]

maximize_heading_levels = false # Shift heading levels higher as much as possible
maximum_heading_level = 6 # The maximum heading level to shift heading levels to
minimize_heading_levels = false # Shift heading levels lower as much as possible
minimum_heading_level = 2 # The minimum heading level to shift heading levels to
normalize_heading_levels = false # Shift heading levels higher to fill heading level gaps
```

Hope that helps!

**Comment by flyingflo** [comment]
Thanks for your effort @willfaught !
